### ISSUE TITLE
Make Circle CI run the tests using both node 4 and latest node

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#57]
<a href="https://github.com/lucetius"><img src="https://avatars2.githubusercontent.com/u/3426608?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lucetius](https://github.com/lucetius)**
_Friday Oct 14, 2016 at 14:27 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/497_

----

Circle uses `nvm` so you can set the node version based on some conditional logic in `circle.yml` 

Something like the following should help:

``` yaml
dependencies:
  pre:
    - case $CIRCLE_NODE_INDEX in 0) NODE_VERSION=4 ;; 1) NODE_VERSION=5 ;; 2) NODE_VERSION=6 ;; esac; nvm install $NODE_VERSION && nvm alias default $NODE_VERSION

test:
  override:
    - ./<your-test-command>
```
